---
target:
  registry: 162258779877.dkr.ecr.us-east-1.amazonaws.com
  prefix: "npr/"

repositories:
  - name: nginx
    match_tag:
      - "stable-alpine"
      - "latest"
      - "1.19.10-alpine"
      - "1.20.1-alpine"
      - "1.21.0-alpine"
      - "alpine"
      - "1.12-alpine"
      - "1.17.4"
  
  - name: node
    match_tag:
      - "12"
      - "14"
      - "16"
      - "12-alpine3.11"
      - "14-alpine3.13"
      - "16-alpine3.13"
      - "12-slim"
      - "14-buster"
      - "10-slim"
      - "10-alpine"
      - "14.15.4"
      - "8.16.1-stretch-slim"
      - "10.1.0"
      - "6.9.5-alpine"
      - "9-slim"
      - "carbon"
      - "8-alpine"
  
  - name: amazon/aws-cli
    match_tag: 
      - "2.0.9"
      - "latest"
  
  - name: brettt89/silversripe-web
    match_tag: 
      - "7.4-apache"
  
  - name: selenium/standalone-chrome-debug
    match_tag: 
      - "latest"
  
  - name: python
    match_tag: 
      - "3.8-buster"
      - "3.9-buster"
  
  - name: mariadb
    match_tag:
      - "latest"
  
  - name: php
    match_tag:
      - "8.0-fpm-alpine3.13"
      - "7.2.27-fpm-stretch"
      - "7.4.11-fpm-alpine3.12"
      - "7.4-fpm-alpine3.12"
      - "7.4.12-cli-alpine3.12"
      - "7.1-apache"
      - "7-fpm"
      - "5-cli"
      - "5.6-apache"
      - "7.3.8-fpm-stretch"
  
  - name: ubuntu
    match_tag: 
      - "14.04"
      - "18.04"
      - "16.04"
      - "20.04"
  
  - name: golang
    match_tag:
      - "alpine"
  
  - name: alpine
    match_tag:
      - "latest"
      - "3.13"
      - "3.8"
      - "3.7"
  
  - name: debian
    match_tag:
      - "buster-slim"
      - "jessie"
  
  - name: mongo
    match_tag: 
      - "2.2.7"
  
  - name: jenkins/ssh-agent
    match_tag:
      - "latest"
  
  - name: jenkins/jenkins
    match_tag:
      - "2.149"
      - "latest"
  
  - name: elasticsearch
    match_tag:
      - "6.2.3"
      - "2.4.6"
  
  - name: httpd
    match_tag: 
      - "2.4"
  
  - name: mysql
    match_tag: 
      - "5.7"
  
  - name: amazonlinux
    match_tag: 
      - "1"
  
  - name: redis
    match_tag: 
        - "5.0"
  
  - name: percona
    match_tag: 
        - "5.7"
  
  - name: rundeck
    match_tag: 
        - "3.0.7"
  
  - name: fluent/fluentd-kubernetes-daemonset
    match_tag: 
      - "elasticsearch"
  
  - name: phpdockerio/php73-fpm
    match_tag: 
      - "latest"
      
  - name: keymetrics/pm2
    match_tag:
      - "latest-stretch"
  
  - name: rabbitmq
    match_tag:
      - "3-management"